### ISSUE TITLE
Set up compat helper in this repo

### ISSUE THREAD

**Issue by sefffal** [JuliaAstro/Reproject.jl#11]
This package is stuck on an older version of FITSIO, which is pretty quick to fix. 
but we should set up compathelper to catch this faster in future.

**Comment by giordano** [comment]
CompatHelper is [already there](https://github.com/JuliaAstro/Reproject.jl/blob/04006f0c60e69635671a0396dcb3161bec952af9/.github/workflows/CompatHelper.yml), but it probably stopped for inactivity.

**Comment by sefffal** [comment]
Ah got it!
I’ll just wait for CI to complete and then I’ll merge the compat helper PRs.
